# Generated by Django 3.0.5 on 2020-09-27 12:00

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CambioMecanico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Fecha creación')),
                ('modified', models.DateTimeField(auto_now=True, db_column='modificado', verbose_name='Fecha modificado')),
                ('fecha_fin', models.DateTimeField(verbose_name='Fin cambio')),
            ],
            options={
                'verbose_name': 'Cambio mecánico',
                'verbose_name_plural': 'Cambios Mecánicos',
                'db_table': 'cambio_mecanico',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, unique=True)),
                ('id_jefe', models.IntegerField(verbose_name='Identificación Jefe')),
                ('created', models.DateTimeField(auto_now=True, db_column='creado', verbose_name='Fecha de alta')),
                ('modified', models.DateTimeField(auto_now=True, db_column='modificado', verbose_name='Fecha modificado')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'db_table': 'categoria',
            },
        ),
        migrations.CreateModel(
            name='FichaTecnica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=True, verbose_name='Ficha Técnica Activo')),
                ('created', models.DateTimeField(auto_now=True, db_column='creado', verbose_name='Fecha de alta')),
                ('modified', models.DateTimeField(auto_now=True, db_column='modificado', verbose_name='Fecha modificado')),
                ('delete', models.DateField(blank=True, null=True, verbose_name='Fecha baja')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ficha Técnica',
                'verbose_name_plural': 'Fichas Técnicas',
                'db_table': 'ficha_tecnica',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Impresora',
            fields=[
                ('impresora_id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('created', models.DateTimeField(auto_now=True, db_column='creado', verbose_name='Fecha de alta')),
                ('modified', models.DateTimeField(auto_now=True, db_column='modificado', verbose_name='Fecha modificado')),
                ('activo', models.BooleanField(default=True, verbose_name='Impresora Activa')),
                ('delete', models.DateField(blank=True, null=True, verbose_name='Fecha baja')),
            ],
            options={
                'db_table': 'impresora',
                'ordering': ['impresora_id'],
            },
        ),
        migrations.CreateModel(
            name='Operario',
            fields=[
                ('legajo', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('created', models.DateTimeField(auto_now=True, db_column='creado', verbose_name='Fecha de alta')),
                ('modified', models.DateTimeField(auto_now=True, db_column='modificado', verbose_name='Fecha modificado')),
                ('activo', models.BooleanField(verbose_name='Operario Activo')),
                ('delete', models.DateField(blank=True, null=True, verbose_name='Fecha baja')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelBaseApp.Categoria')),
            ],
            options={
                'db_table': 'operario',
                'ordering': ['legajo'],
            },
        ),
        migrations.CreateModel(
            name='Parada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40, unique=True)),
                ('created', models.DateTimeField(auto_now=True, db_column='creado', verbose_name='Fecha de alta')),
                ('modified', models.DateTimeField(auto_now=True, db_column='modificado', verbose_name='Fecha modificado')),
                ('active', models.BooleanField(default=True, verbose_name='Ficha Técnica Activo')),
                ('sector_asignado', models.CharField(choices=[('TINTAS', 'TINTAS'), ('MONTAJE', 'MONTAJE'), ('DEPÓSITO', 'DEPÓSITO'), ('MANTENIMIENTO', 'MANTENIMIENTO'), ('PROGRAMACIÓN', 'PROGRAMACIÓN'), ('SUPERVICIÓN', 'SUPERVICIÓN'), ('PRODUCCIÓN', 'PRODUCCIÓN'), ('OPERATIVO', 'OPERATIVO'), ('CALIDAD', 'CALIDAD')], max_length=30)),
                ('delete', models.DateField(blank=True, null=True, verbose_name='Fecha baja')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'parada',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Setup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Fecha creación')),
                ('fecha_fin', models.DateTimeField(verbose_name='Fin Setup')),
                ('parada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modelBaseApp.Parada', verbose_name='Parada')),
            ],
            options={
                'verbose_name': 'Setup',
                'verbose_name_plural': 'Setups',
                'db_table': 'setup',
            },
        ),
        migrations.CreateModel(
            name='Produccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Fecha de creación')),
                ('fecha_fin', models.DateTimeField(verbose_name='Fin producción')),
                ('parada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modelBaseApp.Parada', verbose_name='Parada')),
            ],
            options={
                'verbose_name': 'Producción',
                'verbose_name_plural': 'Producciones',
                'db_table': 'produccion',
            },
        ),
        migrations.CreateModel(
            name='ParteImpresion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateField(auto_now=True, verbose_name='Fecha creación')),
                ('metros_registro', models.IntegerField(verbose_name='Metros registro')),
                ('kg_registro', models.IntegerField(verbose_name='Kg. registro')),
                ('metros', models.IntegerField(verbose_name='Metros producidos')),
                ('kg', models.IntegerField(verbose_name='Kg producidos')),
                ('ayudante1ero', models.ForeignKey(db_column='ayudante1er', on_delete=django.db.models.deletion.DO_NOTHING, related_name='ayudante1er', to='modelBaseApp.Operario', verbose_name='Primer ayudante')),
                ('ayudante2do', models.ForeignKey(db_column='ayudante2do', on_delete=django.db.models.deletion.DO_NOTHING, related_name='ayudante2do', to='modelBaseApp.Operario', verbose_name='Segundo ayudante')),
                ('cambio', models.ManyToManyField(blank=True, db_column='cambio_id', related_name='cambio', to='modelBaseApp.CambioMecanico', verbose_name='Cambio Mecánico')),
                ('fichaTecnica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelBaseApp.FichaTecnica')),
                ('impresora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelBaseApp.Impresora')),
                ('maquinista', models.ForeignKey(db_column='maquinista', on_delete=django.db.models.deletion.DO_NOTHING, related_name='maquinista', to='modelBaseApp.Operario', verbose_name='Maquinista')),
                ('produccion', models.ManyToManyField(blank=True, db_column='produccion', related_name='produccion', to='modelBaseApp.Produccion', verbose_name='Producción')),
                ('setup', models.ManyToManyField(blank=True, db_column='setup', related_name='setup', to='modelBaseApp.Setup', verbose_name='RM AC AP')),
                ('supervisor', models.ForeignKey(db_column='supervisor', on_delete=django.db.models.deletion.DO_NOTHING, related_name='supervisor', to='modelBaseApp.Operario', verbose_name='Supervisor')),
            ],
            options={
                'verbose_name': 'Parte de impresión',
                'verbose_name_plural': 'Partes de impresión',
                'db_table': 'parte_impresion',
            },
        ),
        migrations.AddField(
            model_name='cambiomecanico',
            name='parada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='modelBaseApp.Parada', verbose_name='Parada'),
        ),
        migrations.AddField(
            model_name='cambiomecanico',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
