# Generated by Django 3.0.5 on 2020-09-27 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelBaseApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cambiomecanico',
            old_name='created',
            new_name='create',
        ),
    ]
