# Generated by Django 3.0.5 on 2020-09-27 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelBaseApp', '0002_auto_20200927_0912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cambiomecanico',
            name='user',
        ),
    ]
